### ISSUE TITLE
Add keyboard shortcut to Ledger congrats screen

### ISSUE THREAD

**Issue by VladUXUI** [tahowallet/extension#1064]
Since we can't have a button to open Ledger, let's add the shortcut instructions.
It's also a good way to introduce the instructions.

<img width="516" alt="image" src="https://user-images.githubusercontent.com/80846886/156312718-f37e41da-a62d-42fd-bd6f-7f5b01a61b54.png">

[Link to figma](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=6062%3A150919)

**Comment by beemeeupnow** [comment]
can be closed, exists in current version
