### ISSUE TITLE
Make auto lock timer a menu adjustable parameter

### ISSUE THREAD

**Issue by Naxsun** [tahowallet/extension#1151]
### Discord Discussion Link

n/a

### What would you like to be able to do?

Be able to determine after which duration the wallet auto locks, currently set at 30 minutes I believe

**Comment by beemeeupnow** [comment]
duplicates #236

**Comment by Shadowfiend** [comment]
Great catch, going to close that in favor of this since this issue is more user-facing.

**Comment by beemeeupnow** [comment]
can be closed.
  
Added in v0.42.0 via #3477
