### ISSUE TITLE
Transaction Details - Add header

### ISSUE THREAD

**Issue by VladUXUI** [tahowallet/extension#1167]
Our transaction details need a bit of love .

Currently we don't have title implemented. So once you click on the transaction in activity you no longer know what transaction it is.
Components are Icon + Tx type + Button(icon) for Etherscan.

Should look something like this
<img width="418" alt="image" src="https://user-images.githubusercontent.com/80846886/158431786-46e0d770-2a13-4715-b161-a1aa5314249a.png">

[Link to Figma](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=6%3A0)

**Comment by Shadowfiend** [comment]
How does this interact with the ledger connection indicators? Are they above or below? Praying for below lol.

**Comment by VladUXUI** [comment]
This is for the Transaction details page(clicking on an activity item), so no Ledger indicator to worry about :D

**Comment by rootial** [comment]
Hi @VladUXUI , i'd like to take a look this task. 
can you grant me access to the figma? my gmail address is brightliu77@gmail.com
thanks very much.
