### ISSUE TITLE
Migrate key derivation from PBKDF to Argon2

### ISSUE THREAD

**Issue by mhluongo** [tahowallet/extension#1328]
A memory-hard key derivation function will make [cracking existing wallet files](https://twitter.com/MetaMask/status/1515727239391809536) far more difficult.

This has been discussed for a post-DAO release in tandem with a full extension audit.

**Comment by 0xDaedalus** [comment]
This would be great to do as part of either the private key import or the seed recovery work

**Comment by beemeeupnow** [comment]
seems this was added as of v0.42.0 via #3502 unless this covers some other area
