### ISSUE TITLE
Score assets by trust

### ISSUE THREAD

**Issue by mhluongo** [tahowallet/extension#1893]
Assets that have been...

- included in a configured token list
- sent by a tracked address, either directly or via a contract call
- found in an Alchemy balance check
- flagged as trusted

... should always be displayed in the UI.

Assets that have been...

- flagged as ignored / untrusted
- included in a configured scam token list

... shouldn't be displayed in the UI or balance checked.

**Comment by Shadowfiend** [comment]
Closing this out in favor of #1021 , which is overlapped enough to be addressing most of what this ticket covers.
