### ISSUE TITLE
Can't lock tokens for governance on curve mainnet (CRV --> veCRV)

### ISSUE THREAD

**Issue by morisschulzersson** [tahowallet/extension#2354]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/944337346684391474/1025695446477320243

### What browsers are you seeing the problem on?

Brave

### What were you trying to do?

I tried to lock veCRV on Curve for governance on mainnet for four years. I was able to swap from eth to crv but wasn't able to lock the tockens for governance (https://dao.curve.fi/locker).

### What did not work?

I wasn't able to connect tally with the curve dao website and following warning appeared: 
<img width="880" alt="Bildschirmfoto 2022-09-30 um 19 56 51" src="https://user-images.githubusercontent.com/84903235/193515422-17deb898-4914-4f03-9e3e-7f0d2b86585e.png">

### Version

v0.16.3

**Comment by Shadowfiend** [comment]
As far as I can tell, this is fully working now. Closing, but please reopen if you're still having issues.
