### ISSUE TITLE
New copy for `Activity` tab when connected to networks alchemy does not support

### ISSUE THREAD

**Issue by 0xDaedalus** [tahowallet/extension#2422]
The won't be accurate since we likely won't have the ability to add historical transactions over time.

<img width="361" alt="image" src="https://user-images.githubusercontent.com/94649004/195604727-68dd3bd8-9ebf-4c36-844c-83f8f46bb16b.png">

**Comment by VladUXUI** [comment]
New activity that you have from the moment you activated this network will show up here.

Confirming that this is true? ^^ CC @0xDaedalus

**Comment by 0xDaedalus** [comment]
Confirmed ✅

**Comment by VladUXUI** [comment]
Let's change to:

"All your new transaction will show up here"

WDYT?
