### ISSUE TITLE
Tabbed Onboarding: Ui Fixes

### ISSUE THREAD

**Issue by VladUXUI** [tahowallet/extension#2631]
## Possible bug but idk for sure
- [ ] The onboarding should open automatically as soon as i install the extension

## Overall

- [ ] Size of the icon is 120px, it should be 80px
<img width="346" alt="image" src="https://user-images.githubusercontent.com/80846886/202138244-eb3c2b07-fd76-4d2a-ae36-8c93d3359a1c.png">

## Use Existing wallet
 - [ ] Mouse over should be orange for icon as well
- [ ] Spacing here is not quite right. Too much space on top and bottom
<img width="387" alt="image" src="https://user-images.githubusercontent.com/80846886/202130465-8a3426e9-83c9-4b47-a100-86afe45391fc.png">

## Password Page
- [ ] Icon for Password is not the right one
<img width="444" alt="image" src="https://user-images.githubusercontent.com/80846886/202130811-8c8ca495-4aed-4cce-8bf3-2ce4616ca511.png">
- [ ] Begin the hunt button should be disabled until password is written down twice
- [ ] When you are in first input, pressing tab should take you to second input

## Import Secret recovery phrase
- [ ]  Clear formatting when users paste in a seedphrase. Right now it keeps the formatting from source of copy

## New recovery phrase
- [ ]  When clicking on copy to clipboard, we need a snackbar saying "copied to clipboard"
- [ ] Congratulation screen content should be centred
<img width="527" alt="image" src="https://user-images.githubusercontent.com/80846886/202135329-a77c50b8-6463-4374-9cef-8636d7f01141.png">

## Read Only

- [ ] Icon size is different from others, it is set to 120px, but that size also includes the eye icon, hence making the yellow logo smaller. I would recommend we use just 1 SVG for this, and change the colour accordingly

**Comment by greg-nagy** [comment]
> Can I fix this?

Hey hey!

It's fantastic that you want to work on this!

We plan to release this next week, so the schedule is tight. 
But we probably won't get to this task until Monday or Tuesday. 
If you feel confident that you can tackle this in this time window, that would be an amazing help! 

If you don't want to work with this tight schedule that's also ok, we will take care of this, 
and you can choose another good first issue. 

I will leave the decision to you, and whatever you choose, your intent is appreciated!

**Comment by frankiefab100** [comment]
> > Can I fix this?
> 
> Hey hey!
> 
> It's fantastic that you want to work on this!
> 
> We plan to release this next week, so the schedule is tight. But we probably won't get to this task until Monday or Tuesday. If you feel confident that you can tackle this in this time window, that would be an amazing help!
> 
> If you don't want to work with this tight schedule that's also ok, we will take care of this, and you can choose another good first issue.
> 
> I will leave the decision to you, and whatever you choose, your intent is appreciated!

I think I would try working on another open issue.

**Comment by hyphenized** [comment]
Addressed in #2510
