### ISSUE TITLE
Add support zksync network

### ISSUE THREAD

**Issue by calvinomni** [tahowallet/extension#2726]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/875438141610270740

### What would you like to be able to do?

1. Add Tally Ho on mobile app
2. Add Wallet Connect 
3. Add zksync network

**Comment by Shadowfiend** [comment]
We've lost the original message here somehow, but it feels like this is fixed now that we support adding zkSync via ChainList?

**Comment by jagodarybacka** [comment]
yup and we even support NFTs on zkSync, will close it as mobile support and wallet connect are tracked elsewhere
