### ISSUE TITLE
Seed Verification breaks if user verifies seed and then removes a word

### ISSUE THREAD

**Issue by 0xDaedalus** [tahowallet/extension#2755]
Definitely an edge case - but important to capture:

https://user-images.githubusercontent.com/94649004/207382187-260cc273-d0d2-45df-b203-aa3d7bd1a35f.mov

**Comment by tallysam** [comment]
This is fixed in the tabbed onboarding #2510

**Comment by kkosiorowska** [comment]
Fixed in https://github.com/tahowallet/extension/pull/2510
