### ISSUE TITLE
Clickable Area on some elements in tabbed onboarding is inconsistent

### ISSUE THREAD

**Issue by 0xDaedalus** [tahowallet/extension#2756]
https://user-images.githubusercontent.com/94649004/207382834-ebaa83ca-768d-43cf-94ad-364840a4d331.mov

https://user-images.githubusercontent.com/94649004/207382844-420353e4-fe8d-44b3-9dda-527a5a2defd6.mov

**Comment by hyphenized** [comment]
Fixed in #2510
