### ISSUE TITLE
Define/decide the connection flow for wallet connect

### ISSUE THREAD

**Issue by greg-nagy** [tahowallet/extension#2771]
We have multiple options on how to start the communication flow 

## Questions: 
- Do we want to get into the wallet connect registry OR we want to inject tally icon on the desktop page? 
  - If we want to get into the registry we need a url that opens when the button is pressed and that url will start the connection flow [Similar to tokenary](https://tokenary.io/wc?uri=wc%3A3df9fb70-201f-4ed9-92fc-27448e592db5%401%3Fbridge%3Dhttps%253A%252F%252F8.bridge.walletconnect.org%26key%3D2c6a55573abc1ab8c3276e019f9b535794d240451a408058dfcec57004999447)
- Do we want to display a page when the URL is opened, OR we want to start the communication with the wallet and close the tab automatically. 
  - OR we don't want to open a tab at all — only possible if we inject the button

## Options to choose from
- registry + new tab/webpage — robust, stable, distribution channel (tally will be in every dapp that implements wallet connect and we can get them to install from the webpage)
- inject + new tab/webpage — fairly robust, fairly stable, only works if user has tally installed
- inject + open communication directly — a bit hacky but probably would work

From dev effort perspective they are similar.

Blocks #2689, #2690, #2692

**Comment by VladUXUI** [comment]
This has been decided, and we are going to do the inject + open communication directly.

Will come back to "registry+new tab" once we have a path forward
