### ISSUE TITLE
Failing to set-up transactions & not getting price feeds

### ISSUE THREAD

**Issue by Naxsun** [tahowallet/extension#2920]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Users reported issues setting up transactions. 'Failed to broadcast' and/or 'dropped transactions'

User screenshots also showed missing USD prices. Unknown if these are related / an indicator for the issue with the transactions.

Aligned with @jagodarybacka to add these in 1 ticket to look into and possibly split up in multiple tickets.

### What did not work?

https://discord.com/channels/808358975287722045/888500174685614090/1067013709576282173
https://discord.com/channels/808358975287722045/888500174685614090/1066694369366782023
https://discord.com/channels/808358975287722045/930169481660104725/1065264431094824980

### Version

v0.19.0

**Comment by mr-michael** [comment]
Wondering if we can close this?
