### ISSUE TITLE
Investigate scrolling performance of NFT page of accounts with large amounts of NFTs

### ISSUE THREAD

**Issue by 0xDaedalus** [tahowallet/extension#2953]
Network requests to fetch nft pfp's resolve in a very reasonable amount of time (<40s) but there is still a significant amount of lag between network request resolving and the pfp loading in the UI.  This could be an edge case for profiles with large amounts of NFTs but worth investigating to make sure if that is the case or not.

https://user-images.githubusercontent.com/94649004/215788880-c536e22e-490c-4280-9424-5aff4b362602.mov

**Comment by jagodarybacka** [comment]
Possible solutions:
- list virtualization
  - **why:** as big accounts have a lot of collections the list is huge and just an amount of DOM nodes is so big it makes it heavy for both React VDOM and regular browser
  - **how:** if we would like to make this list virtual then we will have to write our own custom solution. We tried using popular list virtualization libs before (in prev ver of NFTs feature) but it was not suitable and we reverted it in the end. This version contains even more custom animations and list features.
 - reducing redux slice size
   - **how:** as we are keeping info about collections in redux we can remove MOST of the data when user is not actively using NFTs page or NFTs tab on Wallet page. 
   - **problems:** this will cause more loading time as we will need to load the data from the database back to the redux state every time that data is needed
 - separate redux store
   - **why:** right now we have a single redux store that keeps all the data about everything, as that data storage gets bigger more browser memory it needs and browser is unable to optimize it
   - **how:** making separate redux store would solve problems with big slices consuming browser memory - activities, assets, nfts. 

to be continued with other ideas...

**Comment by tallysam** [comment]
Hey @VladUXUI could you just let us know the average number of NFTs held by addresses (in general) of all NFT holders?

**Comment by VladUXUI** [comment]
I couldn't track down the guesstimation. Let's go with 100 :)

**Comment by jagodarybacka** [comment]
> premature optimization

I agree, as this was more like a spike ticket I think we are good to close it, what do you think @tallysam?
