### ISSUE TITLE
Not properly displayed table in portfolio page 

### ISSUE THREAD

**Issue by kkosiorowska** [tahowallet/extension#2989]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Check portfolio page. 

### What did not work?

The table is cut, the padding is missing.

![Screenshot 2023-02-06 at 11 20 22](https://user-images.githubusercontent.com/23117945/216947584-33844b1c-9b75-4ac2-b722-25cd9697951d.png)

### Version

v0.21.2

**Comment by xpaczka** [comment]
This is already done
