### ISSUE TITLE
Investigate possible Ledger failure blocking signing

### ISSUE THREAD

**Issue by jagodarybacka** [tahowallet/extension#3031]
Related PR: https://github.com/tallyhowallet/extension/pull/2796/files

The fix it implements possibly breaks if a Ledger transport is no longer valid.  We should investigate if this blocks signing with non-Ledger accounts as well as it throws an exception before anything else gets to happening

**Comment by Shadowfiend** [comment]
This def does break signing for non-Ledger accounts 😬  I've seen it pretty consistently.
