### ISSUE TITLE
Update import page validation to validate and accept private keys

### ISSUE THREAD

**Issue by 0xDaedalus** [tahowallet/extension#3069]
The import page's form validation does not currently accept private keys.  Lets change it to:
- Accept private keys
- Display an error message that applies to both private keys and seed phrases
- Support text-wrapping so that pasted private keys do not underflow as in the screenshot.

<img width="357" alt="image" src="https://user-images.githubusercontent.com/94649004/220665380-a424e46e-21af-494d-b9a2-8c5ef6fe07b6.png">

**Comment by jagodarybacka** [comment]
Tabbed onboarding designs were updated to include pk import 
![image](https://user-images.githubusercontent.com/20949277/223097552-a1d68bd6-e5dc-4732-a903-6a19f4fbce5a.png)

**Comment by jagodarybacka** [comment]
Closing as this is done as a part of https://github.com/tahowallet/extension/pull/3089
