### ISSUE TITLE
Ether marked as untrusted after version update

### ISSUE THREAD

**Issue by jagodarybacka** [tahowallet/extension#3076]
### To reproduce
- checkout old version like 0.16.0 and install extension as such
- update to newest main and update extension

Result: ETH is marked as untrusted on Ethereum
![image](https://user-images.githubusercontent.com/20949277/220980999-45dfc991-0e91-44f6-8bd0-fd36707862f2.png)

**Comment by hyphenized** [comment]
Network base asset persisted in UI slice is outdated
