### ISSUE TITLE
Network icon on transaction screen is missing

### ISSUE THREAD

**Issue by jagodarybacka** [tahowallet/extension#3093]
there is no network icon on sign transaction screen
![image](https://user-images.githubusercontent.com/20949277/221843955-8c8d5703-4782-49bc-b236-6f25f906e6cb.png)

**Comment by scorcism** [comment]
Can i work on this ?

**Comment by scorcism** [comment]
Can i work on this ?

**Comment by jagodarybacka** [comment]
@scorcism sure!

**Comment by turjoc120** [comment]
Hi, @jagodarybacka can you tell me where can i find the network icon?

**Comment by jagodarybacka** [comment]
@turjoc120 we are using these icons in many places, in the top bar or the networks selector for example 😄

**Comment by scorcism** [comment]
@turjoc120 you are working on this ? 😶

**Comment by turjoc120** [comment]
@scorcism No, I was going through the codes

**Comment by scorcism** [comment]
@jagodarybacka I'm unable to find this. Can you guide me little bit ?
