### ISSUE TITLE
Tabbed onboarding - correct "view-only"

### ISSUE THREAD

**Issue by mr-michael** [tahowallet/extension#3102]
In the onboarding flow, we sometimes use the term "view-only" or "view only". These all need to be corrected to "read-only."

Here are the places where I saw "view-only" used:

**When you add a read-only wallet**
<img width="381" alt="Screenshot 2023-03-01 at 3 23 08 PM" src="https://user-images.githubusercontent.com/7005061/222277383-6f293651-8f71-4b69-8ba0-2b726972693f.png">

**On the left panel**
<img width="460" alt="Screenshot 2023-03-01 at 3 23 40 PM" src="https://user-images.githubusercontent.com/7005061/222277552-54fb479e-43a4-4449-bfc2-3fb9859c527c.png">

**When you start to create a new seed phrase**
<img width="625" alt="Screenshot 2023-03-01 at 3 24 32 PM" src="https://user-images.githubusercontent.com/7005061/222277766-1bc4a059-f0a4-479e-b5fc-72032e10bac2.png">

**Comment by hyphenized** [comment]
Fixed in https://github.com/tahowallet/extension/pull/2956
