### ISSUE TITLE
Tabbed onboarding - formatting re: "save and store your recovery phrase"

### ISSUE THREAD

**Issue by mr-michael** [tahowallet/extension#3103]
We are missing spacing above and below "save and store your recovery phrase", which is causing the "<-" to collide with the text.

The "I wrote it down" button appears to be shorter than other buttons.

"Before we get started" page included for comparison on spacing and button height

<img width="651" alt="Screenshot 2023-03-01 at 3 24 36 PM" src="https://user-images.githubusercontent.com/7005061/222278261-d745d84e-f1b0-4b9c-be9c-e3f43ddfbb02.png">

<img width="625" alt="Screenshot 2023-03-01 at 3 24 32 PM" src="https://user-images.githubusercontent.com/7005061/222278273-d6e59dbb-6505-42a7-9b55-b793467c1502.png">

**Comment by hyphenized** [comment]
Fixed in https://github.com/tahowallet/extension/pull/2956
