### ISSUE TITLE
Tabbed onboarding - pin animation

### ISSUE THREAD

**Issue by mr-michael** [tahowallet/extension#3104]
Says "Tally Ho!"

<img width="415" alt="Screenshot 2023-03-01 at 3 28 45 PM" src="https://user-images.githubusercontent.com/7005061/222278711-c5eb3e30-4498-4d63-aba8-d628d87d555b.png">

**Comment by hyphenized** [comment]
Addressed in https://github.com/tahowallet/extension/pull/2956
