### ISSUE TITLE
Tabbed onboarding - missing periods at ends of sentences

### ISSUE THREAD

**Issue by mr-michael** [tahowallet/extension#3105]
In all the examples below, and whenever we have a full informational sentence, we should follow with a period.

**Left panel**
<img width="460" alt="Screenshot 2023-03-01 at 3 23 40 PM" src="https://user-images.githubusercontent.com/7005061/222280510-65ab0bed-1678-4715-8545-6fad0005018a.png">

**Creating new wallet (in the "(i)" section)**
<img width="625" alt="Screenshot 2023-03-01 at 3 24 32 PM" src="https://user-images.githubusercontent.com/7005061/222280607-9b74cb60-7465-4b2d-bfd5-903e6663846f.png">

**Verifying recovery phrase**
<img width="557" alt="Screenshot 2023-03-01 at 3 28 27 PM" src="https://user-images.githubusercontent.com/7005061/222280688-ee841173-cc34-4f4a-a333-4b654b8a2f15.png">

and here:
<img width="492" alt="Screenshot 2023-03-01 at 3 26 30 PM" src="https://user-images.githubusercontent.com/7005061/222280723-9687031c-3fe6-4567-8d85-ea9b4d0ac22e.png">

**Comment by hyphenized** [comment]
Fixed in https://github.com/tahowallet/extension/pull/2956
