### ISSUE TITLE
Tabbed onboarding - button width on 'import wallet'

### ISSUE THREAD

**Issue by mr-michael** [tahowallet/extension#3106]
Should be same width as input field

<img width="485" alt="Screenshot 2023-03-01 at 3 42 24 PM" src="https://user-images.githubusercontent.com/7005061/222280895-c96b8c5d-26ea-425f-be67-5b1087b1f673.png">

<img width="616" alt="Screenshot 2023-03-01 at 3 41 58 PM" src="https://user-images.githubusercontent.com/7005061/222280896-1aae5ea5-7d25-4179-9b35-aa7abe88e703.png">

**Comment by hyphenized** [comment]
Fixed in https://github.com/tahowallet/extension/pull/2956
