### ISSUE TITLE
Tabbed onboarding - update copy

### ISSUE THREAD

**Issue by mr-michael** [tahowallet/extension#3107]
Let's update to: "Several of Taho's most popular features were developed by our community."

"community" does not need to be capitalized... and in general the current wording is not inspiring enough. (I'm not crazy with my sentence either but <shrug>)

<img width="522" alt="Screenshot 2023-03-01 at 3 41 16 PM" src="https://user-images.githubusercontent.com/7005061/222281069-22546548-da6a-40c4-972f-efbec0ef5a75.png">

**Comment by hyphenized** [comment]
Fixed in https://github.com/tahowallet/extension/pull/2956
