### ISSUE TITLE
Cannot sign typed data requests

### ISSUE THREAD

**Issue by hyphenized** [tahowallet/extension#3122]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

![image](https://user-images.githubusercontent.com/28708889/223348163-c8579901-ad80-48ab-af81-71da81f2fb3e.png)

### What did not work?

Both buttons are disabled

### Version

v0.27.1

**Comment by jagodarybacka** [comment]
This is already resolved by release 0.27.2 https://github.com/tahowallet/extension/pull/3124
