### ISSUE TITLE
Infinite approval even after manually specifying a lower limit

### ISSUE THREAD

**Issue by mhluongo** [tahowallet/extension#3135]
I recently made a deposit on Convex, which requested an infinite approval of a Curve LP token. I edited to approval to 100 of that same token, and signed... only the realize the wallet had reverted to an infinite approval :(

**Comment by kkosiorowska** [comment]
I tried to reproduce this issue, but I couldn't able. However, I noticed that I have happened to confirm transactions without confirming the limit. In that case, the transaction is set with the default limit (Infinite). I have prepared a solution to block the button until the user confirms the limit #3283. It should make sure that the user sets the correct limit
