### ISSUE TITLE
Spike for import account with JSON 

### ISSUE THREAD

**Issue by jagodarybacka** [tahowallet/extension#3144]
Let's understand the lift of doing JSON import

**Comment by jagodarybacka** [comment]
We don't have to document it here if we don't want to, it's just a task to make it visible as an actionable item

**Comment by Shadowfiend** [comment]
Unless we have specific concerns, we should document in public, yes.

**Comment by jagodarybacka** [comment]
Spike has been finished, findings in the [PR](https://github.com/tahowallet/extension/pull/3177)
