### ISSUE TITLE
Custom network - Add or activate networks

### ISSUE THREAD

**Issue by mr-michael** [tahowallet/extension#3149]
Let's update so this only appears when users scrolls to bottom of the page. Currently it's fixed at bottom of page

<img width="373" alt="Screenshot 2023-03-13 at 9 20 12 PM" src="https://user-images.githubusercontent.com/7005061/224870671-d6ad5787-ac3f-4957-b0db-b4812bb03d1b.png">

**Comment by VladUXUI** [comment]
Actually this is not the correct banner for now.
We should use the add network one for now.



![Image](https://user-images.githubusercontent.com/80846886/225335912-4950846f-faaa-42b1-956a-d0398678ad8a.png)
