### ISSUE TITLE
jumper.exchange - wallet listed as Tally Ho, can't connect via this option

### ISSUE THREAD

**Issue by michalinacienciala** [tahowallet/extension#3166]
The Jumper Exchange (https://jumper.exchange/) offers an option to connect via Tally Ho. This connection option doesn't work (nothing happens after clicking it). The connection is possible by choosing MM (if Taho is set to be a default wallet).

We should contact the exchange and ask them to change the name to Taho. And fix the issue with the connection.

**Comment by Naxsun** [comment]
Interesting! There is a way to connect, but it's not how it's supposed to be. If you disable MM, set Taho to default, and then select MM, it connects.

Background logs show:
<img width="338" alt="Screen Shot 2023-03-27 at 13 16 32" src="https://user-images.githubusercontent.com/71384922/227928013-509e41a4-ff74-409b-adcc-8dee5672fa36.png">

**Comment by hyphenized** [comment]
This is a bug on their end, I've already notified them on discord @ https://discord.com/channels/849912621360218112/869893252399128677/1086503128444174427

**Comment by Naxsun** [comment]
Ah I did not know jumper was li.fi! Used to be called transferto.

We're actually in a shared group with them, was started for the DOGyssey. Li.fi was one of the participating projects. Adding you there.

**Comment by Naxsun** [comment]
Fixed by the team of Jumper.

https://github.com/lifinance/jumper.exchange/pull/495/files
