### ISSUE TITLE
 Unify display of values of txs/assets/fees etc

### ISSUE THREAD

**Issue by michalinacienciala** [tahowallet/extension#3175]
There is a number of places where we show a rounded amount/value of a given tx/asset/fee etc.
In some of them we don't show any tooltip and in some we show tooltip with the amount that's the same as in the text we're hovering on.
In some places we show the rounded values without any indicator that the value got approximated and in some we use the `~`, `<` or `...` signs.

It would be good to unify our notation. We don't necessarily want to always display the amounts with the same precision - depending on the context we may want to round to two decimal places, or to six or eight. That's fine. But we should have a way of indicating that the shown amount got approximated. And in most places (although probably not all) where we show 0 or 2 decimal digits, it would be good to show more precise amount in a tooltip on hover.

We should think of a convention we want to use and fix all the places where it's not followed.

Some places we should think about:
1. Total account balance
2. Assets balances (on various views)
3. Values of txs in the Asset history or Activity view
4. Details of transactions
5. Values on `Swap Assets` view
6. NFTs values
7. Portfolio values

As part of this work we could also think whether we want to keep the current behavior regarding use of `,` and `.` in the displayed values. For values in USD we use `.` as a decimal separator (for example `$1,051.63`), whereas for other assets we use `,` as decimal separator (for example `23911,783`). This may be a bit confusing, especially if both notations are used on the same view (like on `Swap Assets` view).

**Comment by VladUXUI** [comment]
Can't really have 1 rule for them all. Some place are worth having 100% accuracy, other places not really. This is due to constraint on space and anything after 3 decimals is usually incalculable by humans or it's value is really low. Some asset with bigger price are different tho. For example most people aren't able to tell the difference between 0.325 eth and 0.3259382.

When we use "~" it means we don't really know the exact price
When we use "<" it means that this is the max amount you will pay (meaning again that we don't know the exact price)
I don't remember us using "..." in asset values or prices. But it probably shouldn't be there?

I do like the hover showing the full amount, but only if it was rounded up/down.

**Comment by VladUXUI** [comment]
Do you have an example of a convention being broken that we might want to look into?

**Comment by michalinacienciala** [comment]
One thing that felt "wrong" to me was display of tx amount when small values are being sent.
For example, when I'm sending 0.005 ETH I see:
<img width="367" alt="image" src="https://github.com/tahowallet/extension/assets/78352137/d759b028-d659-4865-a492-561649106190">
And then on the Activity list:
<img width="374" alt="image" src="https://github.com/tahowallet/extension/assets/78352137/926a9a5f-cb9b-4139-9f65-89b73a71d2a8">
Only when I enter the details of the sent tx I see the full amount:
<img width="373" alt="image" src="https://github.com/tahowallet/extension/assets/78352137/e3059767-9d62-45a9-840b-6b8326746ef8">
So when users are signing the transactions, they don't have a way to make sure if the amount that's being sent really matches what they requested. I personally on that stage would like to see the precise amount that will be sent (either as a normal text, or on hover on the rounded value). I don't mind seing the rounded value on the activity list, especially that we show more precise value after clicking on the transaction (and user can check the exact amount on block explorer).

Another thing that looks off to me is the rounding mechanism on the Activity list - we see that some transactions are listed with the two decimals precision. But when I made tx for 0.009 ETH, it was displayed as a tx for `0 ETH` (if we use 2 decimals precision, I would expect to see `0.01 ETH`, as mathematically 0.009 gets rounded to 0.01, not 0).

When it comes to using `...` in amounts, that's what is used in swaps - see:
<img width="377" alt="image" src="https://github.com/tahowallet/extension/assets/78352137/e22cb7ba-ea89-4b3e-a777-469c1f535826">
