### ISSUE TITLE
Can't connect to mirror.xyz

### ISSUE THREAD

**Issue by alsoknownaslj** [tahowallet/extension#3182]
Set Taho as default wallet and tried to connect using the Metamask workaround but it prompted me to use walletconnect or download MM. Recorded below 👇 

https://user-images.githubusercontent.com/104520552/226671353-e475e967-2583-45a3-9bc6-70e32174344d.mov

**Comment by kkosiorowska** [comment]
@alsoknownaslj 
I tried to reproduce it on a version of 0.28.1. I'm able to connect normally. 🤔
What version are you using? Are you able to reproduce the issue again?

**Comment by jagodarybacka** [comment]
I cannot reproduce as well, tried all combinations with Metamask enabled and disabled. @alsoknownaslj what extensions do you have enabled - maybe something else interferes with Taho?
If you still have this issue and can give us a list of other extensions you had - feel free to reopen.
