### ISSUE TITLE
Custom networks - Swaps disabled state

### ISSUE THREAD

**Issue by mr-michael** [tahowallet/extension#3191]
On ALL custom networks, the swaps option appears disabled and presents an error message on hover.

The state should be disabled everywhere:
- Main swap button on wallet page
- Small swap icon on each asset
- Single asset page

![image](https://user-images.githubusercontent.com/80846886/227992628-e3cfa5f5-7d90-4721-9dee-3f8bdae0fdf8.png)

https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=17871-336224&t=AYo0RDWV3sYTA1Bh-4

**Comment by mr-michael** [comment]
@VladUXUI thoughts on this page?

Presumably 'swaps' button should be same 'disabled' color as and same message as on main 'wallet' tab?

<img width="369" alt="Screenshot 2023-03-27 at 11 36 23 AM" src="https://user-images.githubusercontent.com/7005061/227991190-889af817-31ef-407c-846e-f78d50800c82.png">

**Comment by VladUXUI** [comment]
Right, very good catch

Here is a preview

![image](https://user-images.githubusercontent.com/80846886/227992410-d5cd9501-917f-4523-b097-a3cf9fb9d80f.png)

The link is the same in figma. Also added disabled for asset card
