### ISSUE TITLE
Implement Show Recovery Phrase menu option and initial Show Recovery Phrase screen

### ISSUE THREAD

**Issue by 0xDaedalus** [tahowallet/extension#3217]
https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=17769%3A334818&t=NBripafp5rsqcxWM-1

<img width="970" alt="image" src="https://user-images.githubusercontent.com/94649004/229396662-79515b1a-8c1a-4fcf-ac34-0d8311a97de3.png">

- [x] Should only be present for accounts that were imported via recovery phrase.
- [x] Clicking `Show Recovery Phrase` should prompt for password regardless of it wallet is already unlocked or not.
- [x] Implementing the functionality of the `Show Recovery Phrase` screen is not necessary to complete this ticket.

**Comment by jagodarybacka** [comment]
Done as a part of https://github.com/tahowallet/extension/pull/3252
