### ISSUE TITLE
Implement the `Why do I need a recovery phrase` screen

### ISSUE THREAD

**Issue by 0xDaedalus** [tahowallet/extension#3218]
https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=17769-334818&t=NBripafp5rsqcxWM-0

<img width="468" alt="image" src="https://user-images.githubusercontent.com/94649004/229397178-d5f90612-dd5a-4297-ac93-fe783013ae98.png">

- [ ] Link should be added to the `Show Recovery Phrase` screen.
- [ ] If the `WIP` label is still present in the design - check with @VladUXUI before starting on this ticket.

**Comment by VladUXUI** [comment]
let's use this link for now
https://tahowallet.notion.site/Recovery-Phrases-Private-Keys-31274e1abd2e4055aa63dae5297828b3

**Comment by jagodarybacka** [comment]
Done as a part of https://github.com/tahowallet/extension/pull/3252
