### ISSUE TITLE
Implement `Show Recovery Phrase` functionality.

### ISSUE THREAD

**Issue by 0xDaedalus** [tahowallet/extension#3220]
https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=17769-334818&t=NBripafp5rsqcxWM-0

<img width="523" alt="image" src="https://user-images.githubusercontent.com/94649004/229397388-b53c78ac-5676-4fc4-905a-aa07ce515828.png">

- [x] Expanding the `# addresses` area should present a list of exportable accounts along with their notional totals.
- [x] Recovery phrase reveal should be gated by the checkbox.
- [x] Mousing over a vertical half of the recovery phrase should only reveal that half of the phrase - respectively.

**Comment by jagodarybacka** [comment]
Done as a part of https://github.com/tahowallet/extension/pull/3252
