### ISSUE TITLE
Implement `Show Private Key` menu option & initial screen

### ISSUE THREAD

**Issue by 0xDaedalus** [tahowallet/extension#3221]
https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=17769%3A334818&t=NBripafp5rsqcxWM-1

<img width="920" alt="image" src="https://user-images.githubusercontent.com/94649004/229397979-e02973d7-d221-4b93-99c8-c060cfe97d05.png">

- [x] Should only be present for accounts that were imported via private key.
- [x] Clicking `Show Private Key` should prompt for password regardless of it wallet is already unlocked or not.
- [x] Implementing the functionality of the `Show Private Key` screen is not necessary to complete this ticket.

**Comment by jagodarybacka** [comment]
Done as a part of https://github.com/tahowallet/extension/pull/3252
