### ISSUE TITLE
Implement `Show Private Key` screen functionality

### ISSUE THREAD

**Issue by 0xDaedalus** [tahowallet/extension#3222]
https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=17769-334818&t=NBripafp5rsqcxWM-0

<img width="769" alt="image" src="https://user-images.githubusercontent.com/94649004/229398180-c0253087-9802-4332-975f-982db9f0d039.png">

- [x] Private key reveal should be gated by the checkbox.

**Comment by jagodarybacka** [comment]
Done as a part of https://github.com/tahowallet/extension/pull/3252
