### ISSUE TITLE
Implement `What is a private key` screen

### ISSUE THREAD

**Issue by 0xDaedalus** [tahowallet/extension#3223]
https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=17769-334818&t=NBripafp5rsqcxWM-0

<img width="334" alt="image" src="https://user-images.githubusercontent.com/94649004/229398443-22e958bd-9a62-46f7-a2d0-5cf977f3a55f.png">

- [x] Link should be added to the `Show Private Key` screen.
- [x] If the `WIP` label is still present in the design - check with @VladUXUI before starting on this ticket.

**Comment by VladUXUI** [comment]
Let's use this link for now
https://tahowallet.notion.site/Recovery-Phrases-Private-Keys-31274e1abd2e4055aa63dae5297828b3

**Comment by jagodarybacka** [comment]
Done as a part of https://github.com/tahowallet/extension/pull/3252
