### ISSUE TITLE
Implement functionality to let users designate tokens they wish to trust

### ISSUE THREAD

**Issue by 0xDaedalus** [tahowallet/extension#3226]
https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=7523%3A183113&t=NBripafp5rsqcxWM-1

<img width="549" alt="image" src="https://user-images.githubusercontent.com/94649004/229400290-140d083e-7773-4930-9608-7b0c351a2a75.png">

- [ ] Keep in mind that a scan website may not be available on custom chains.

**Comment by hyphenized** [comment]
Done in #3394
