### ISSUE TITLE
Can't correctly import account using recovery phrase when it was earlier imported using private key and removed

### ISSUE THREAD

**Issue by michalinacienciala** [tahowallet/extension#3276]
Steps to reproduce:
1. After unpacking the extension import at least one account (with whatever method).
2. Add some other account using private key. Added under `Private key` category.
3. Remove that account. Removed
4. Add that account using recovery phrase. Added under `Read Only` account (NOOK).
5. Remove that account. Removed.
6. Add that account using recovery phrase. Not added at all (NOOK)

If after that the account is added using private key, it's added correctly. 

Observed on: [extension-builds-3266](https://github.com/tahowallet/extension/suites/12238675333/artifacts/647467018)

**Comment by jagodarybacka** [comment]
Fixed in #3282
