### ISSUE TITLE
Integrate Taho in Chainlist - Logo

### ISSUE THREAD

**Issue by Naxsun** [tahowallet/extension#3278]
### Discord Discussion Link

n/a

### What would you like to be able to do?

NOTE: Ping Nax when we submitted a PR, so he can flag to the Chainlist team.

Taho can already connect to chainlist.org, when set to default. However, it still shows the MetaMask logo when connected. See below:

![image](https://user-images.githubusercontent.com/71384922/232702780-fae6ec41-f4d5-41e8-9e58-db8355c11113.png)

Ideally we'd update this to show the Taho logo when Taho is connected. Additionally we could attempt to also have the Taho name show on the 'add to wallet' button, see below.

Coinbase successfully integrated, see below PR and screenshot. 
https://github.com/DefiLlama/chainlist/pull/119
![image](https://user-images.githubusercontent.com/71384922/232702833-e1461ef2-c1a7-4d01-823b-b3ca20eb882d.png)

I've reached out to Chainlist / Defillama and got below response:
![image](https://user-images.githubusercontent.com/71384922/232703062-19217fbd-00af-4c3e-a814-139f5e727bd0.png)

**Comment by GermaVinsmoke** [comment]
https://github.com/DefiLlama/chainlist/pull/458
I was gonna do this 2 days ago but saw that it's already merged.

**Comment by Shadowfiend** [comment]
This is indeed done, closing.
