### ISSUE TITLE
Better error message for JSON import

### ISSUE THREAD

**Issue by jagodarybacka** [tahowallet/extension#3279]
Let's improve error message to capture incorrect JSON structure

Original comment: 
> When I tried to import `.json` file with JSON content which did not contain the fields needed for key decryption (it was just some random, non-crypto related json file), I saw `Wrong password, make sure you enter the password you used when encrypting this file`. I think we should either detect that the file does not follow expected format (probably harder, as may require defining JSON Schema for Web3 Secret Storage Definition Standard) or change the error message to something like `Wrong password or incorrect file structure, make sure you enter the password you used when encrypting this file and that the file is not corrupted`.

_Originally posted by @michalinacienciala in https://github.com/tahowallet/extension/issues/3266#issuecomment-1512534615_

**Comment by VladUXUI** [comment]
The error is not too user friendly. Wrong file structure and check if it’s not corrupted are not things user can resolve/fix.

let’s change to:
Wrong password or incorrect file. Ensure file is correct and enter the password you used when encrypting this file. 

We can revisit later and have more details once we add to help center

**Comment by jagodarybacka** [comment]
Done in https://github.com/tahowallet/extension/pull/3293
