### ISSUE TITLE
Design QA for Custom networks + custom tokens

### ISSUE THREAD

**Issue by VladUXUI** [tahowallet/extension#3295]
Qa-ing this build https://github.com/tahowallet/extension/pull/3147

### Custom networks
- [x] #3298

### Custom tokens
- [x]  Custom tokens that are added should not be untrusted (i can't test this myself, but getting it from other screenshots)

- [x] If you have assets with dust, you should still see them in the swap list. Only untrusted assets should be swap-able

- [x] #3297
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/80846886/233428931-817663ec-bb39-4014-9594-5a0a9310641b.png">

- [x] #3296
![image](https://user-images.githubusercontent.com/80846886/233433112-76c08bb8-a69e-44c7-b701-e151adba7cb8.png)

## ⏭️ Can be an update to next release
- [x] Delete network hover should be red
- [x] #3310

## Non extension related
- [x] We need to update content on Notion (Vlad will do this tonight)

**Comment by 0xDaedalus** [comment]
> Custom tokens that are added should not be untrusted (i can't test this myself, but getting it from other screenshots)

I think this is the result of out-of-date screenshots
