### ISSUE TITLE
Custom networks icons have sharp corners

### ISSUE THREAD

**Issue by mr-michael** [tahowallet/extension#3321]
Examples:

<img width="376" alt="Screen Shot 2023-04-26 at 8 27 13 PM" src="https://user-images.githubusercontent.com/7005061/234736198-5890efcd-36b9-4c29-a899-15d7bd66163e.png">
<img width="222" alt="Screen Shot 2023-04-26 at 8 18 41 PM" src="https://user-images.githubusercontent.com/7005061/234736199-b6975887-ae00-43b0-ba12-f7d10c6be796.png">

Compared with the glorious roundness of:

<img width="304" alt="Screen Shot 2023-04-26 at 9 26 31 PM" src="https://user-images.githubusercontent.com/7005061/234736402-d66729e1-e672-4872-ae06-d0fd7da44c14.png">

It appears that if we have an image (e.g. canto or fantom), we use rounded corners, but if there's no image, then we have a square with sharp corners.

This is fine, but is slightly at odds with our softer, rounder, more organic style. Maybe we simply make the squares into circles?

Sidenote: we can probably do something amazing, cool, beautiful, and thematically-aligned in the future with our default network and asset icons

**Comment by VladUXUI** [comment]
Let's use 2px radius for the custom colour
