### ISSUE TITLE
Text cut off @ removing a custom network 

### ISSUE THREAD

**Issue by mr-michael** [tahowallet/extension#3323]
Let's add space for another line and not cut off network name here

<img width="420" alt="Screen Shot 2023-04-26 at 8 27 55 PM" src="https://user-images.githubusercontent.com/7005061/234737251-d71e7f36-5e68-4a5f-8f79-a38fc64401d6.png">

<img width="408" alt="Screen Shot 2023-04-26 at 8 27 51 PM" src="https://user-images.githubusercontent.com/7005061/234737252-f1e404ff-5179-49d3-8aa6-cb567c805069.png">

**Comment by Shadowfiend** [comment]
This is a workaround for an unfortunate limitation in how slide-ups work; dynamic heights based on content are non trivial. 

I do think we need to fix this limitation, which would unblock fixing this issue as well.
