### ISSUE TITLE
Add 'beta' label to custom networks

### ISSUE THREAD

**Issue by mr-michael** [tahowallet/extension#3334]
On network selection: 
"Add network (beta)"

On settings:
"Custom networks (beta)"

<img width="380" alt="Screen Shot 2023-04-27 at 6 11 53 PM" src="https://user-images.githubusercontent.com/7005061/235002377-dfb56a64-2dcb-41a4-85e4-972ef0330d4b.png">

<img width="389" alt="Screen Shot 2023-04-27 at 6 11 48 PM" src="https://user-images.githubusercontent.com/7005061/235002380-ad87f237-6b41-4a03-a0d1-59cf8948fdaf.png">

**Comment by kkosiorowska** [comment]
Done in https://github.com/tahowallet/extension/pull/3335
