### ISSUE TITLE
Can't add USDC on zkSync era

### ISSUE THREAD

**Issue by Naxsun** [tahowallet/extension#3336]
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Adding USDC as a token on zkSync era

### What did not work?

Wallet: Version 0.31.0135a1b4 from https://github.com/tahowallet/extension/pull/3147

Wallet address: https://explorer.zksync.io/address/0xf0ee42aa7a347a2d1e9dbdf5cfc42b66843ab33d

Tried to add USDC, token contract:  0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4

Result in Taho:
<img width="385" alt="Screen Shot 2023-04-28 at 08 50 36" src="https://user-images.githubusercontent.com/71384922/235076563-7f59ad78-6467-4c99-b134-d58af7ab8190.png">

Result in MM:
<img width="356" alt="Screen Shot 2023-04-28 at 08 53 34" src="https://user-images.githubusercontent.com/71384922/235076576-d5429d0c-66df-4bde-ae78-442459fbec37.png">

<img width="361" alt="Screen Shot 2023-04-28 at 08 58 01" src="https://user-images.githubusercontent.com/71384922/235076939-0c654194-ca39-41c9-a8ff-78212a1b16c2.png">

Same applies to WETH: 0x5AEa5775959fBC2557Cc8789bC1bf90A239D9a91

### Version

v0.31.0

**Comment by hyphenized** [comment]
Fixed by adding a chain specific multicall contract address for zkSync era
