### ISSUE TITLE
Use returned ability count endpoint

### ISSUE THREAD

**Issue by mr-michael** [tahowallet/extension#3350]
<img width="368" alt="Screen Shot 2023-05-01 at 5 33 21 PM" src="https://user-images.githubusercontent.com/7005061/235535623-5a4697f6-dc54-4b2d-b064-024bc708e0fa.png">

For # of open abilities, we should be able to use the following endpoint (not previously available)

https://docs.daylight.xyz/reference/get_v1-wallets-address-counts

**Comment by kkosiorowska** [comment]
At this point, there is no need to use this endpoint to show the number of open abilities.The user is able to delete and mark the ability as completed. So the number of abilities in the wallet doesn't match that in the API. So let's close this task. If necessary we will use it.
