### ISSUE TITLE
Can't sign and connect wallet to dapp on zkSyncEra network

### ISSUE THREAD

**Issue by jagodarybacka** [tahowallet/extension#3388]
Can't connect to https://airdrop.zkape.io/#/. After the connection dapp wants to receive a signed message but Taho can't show that screen.

**Comment by Shadowfiend** [comment]
I can't get to [https://airdrop.zkape.io](https://airdrop.zkape.io/#/), we sure that URL is right?

**Comment by jagodarybacka** [comment]
hmm, I think it was working when I was creating that issue, I won't be able to find who was complaining about it so let's close it
