### ISSUE TITLE
Token list is not getting updates

### ISSUE THREAD

**Issue by jagodarybacka** [tahowallet/extension#3391]
Token list saved in extension is not updated with new content

[Extension's token list ](https://ipfs.io/ipfs/bafybeigtlpxobme7utbketsaofgxqalgqzowhx24wlwwrtbzolgygmqorm)

[New token list](https://ipfs.io/ipfs/bafybeianu4bww63ayktccmrwqzyvabgbrqwerswxm5ycn5txyfyoakt3ta) - +30 new tokens

**Comment by Shadowfiend** [comment]
Updating the token list right now requires updating the underlying IPFS address in the extension, as it's content-addressed so updates in content change the address.
