### ISSUE TITLE
Support EIP 2255 (`wallet_requestPermissions`)

### ISSUE THREAD

**Issue by am1993421** [tahowallet/extension#3395]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1108852143030534244

### What would you like to be able to do?

N/A

**Comment by Rom4iG88** [comment]
nothing

**Comment by Shadowfiend** [comment]
Going to try and snipe this once we've implemented the next update to dApp connections, which should be in the next week or two. Appreciate your patience!

**Comment by am1993421** [comment]
> Going to try and snipe this once we've implemented the next update to dApp connections, which should be in the next week or two. Appreciate your patience!

https://discord.com/channels/808358975287722045/888500174685614090/1109544278453129216
Should we support AltLayer testnet bridge website?

**Comment by Shadowfiend** [comment]
Actually ethermail in particular is a bit more complicated. They're using `wallet_requestPermissions` here, which we don't really handle at the moment. We can add partial support that ignores the actual requested permissions (in practice these permission requests are largely unused) and always returns available permissions as `eth_accounts` or something of the sort. Will think on this a little.

**Comment by am1993421** [comment]
https://discord.com/channels/808358975287722045/888500174685614090/1111292414053859349

skurpytown.com
This site has the same problem

**Comment by mhluongo** [comment]
Looks like [FriendTech](https://www.friend.tech/deposit) is also hit by this.

**Comment by Shadowfiend** [comment]
Incidentally it looks like Ethermail no longer requires `wallet_requestPermissions`.
