### ISSUE TITLE
Blank page on disconnected ledger

### ISSUE THREAD

**Issue by jagodarybacka** [tahowallet/extension#3419]
Introduced in v0.34.0

If the Ledger goes to sleep/screensaver and a dapp requests a signature, there is an error and the wallet UI shows up blank.

![Ledger_sleeping](https://github.com/tahowallet/extension/assets/95515141/74a52d83-506a-4b55-abee-488adb50bf5c)

v0.32.0 (working) for reference:
![v0 32 0_check_Ledger](https://github.com/tahowallet/extension/assets/95515141/d55fe6d6-e755-4258-b280-81190f3fe656)

v0.34.0 (broken) and higher:
![v0 34 0_blank](https://github.com/tahowallet/extension/assets/95515141/cf1cc671-901a-4341-bca7-58e01432c801)

_Originally posted by @beemeeupnow in https://github.com/tahowallet/extension/issues/3407#issuecomment-1564524469_

**Comment by Shadowfiend** [comment]
Likely a regression from #3380, possibly due to the `await` I decided to skip in there?

**Comment by Shadowfiend** [comment]
Check in with https://discord.com/channels/808358975287722045/888500174685614090/1114000403160379413 to see if this fix also fixes the issue they're seeing on Brave.
