### ISSUE TITLE
Cannot connect wallet to coinmarketcap.com

### ISSUE THREAD

**Issue by hyphenized** [tahowallet/extension#3430]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1114179647987523614

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Connect the wallet through the Metamask option on https://coinmarketcap.com/

### What did not work?

Instead of connecting, the site redirects you to metamask install page

### Version

v0.34.0

**Comment by Shadowfiend** [comment]
This is another case where we need impersonation.

At this point, we should plan to do dApp connection triage and then switch on impersonation for everything when “use as default” is enabled.
