### ISSUE TITLE
Feature flag cleanup

### ISSUE THREAD

**Issue by Shadowfiend** [tahowallet/extension#3449]
A bunch of feature flags have been enabled for some time but still exist and have alternate code paths. We want to clean these up so we can make new ones a little easier to manage. 

Notable flags are the NFT set and the new signing UI flag.

**Comment by jagodarybacka** [comment]
Do we want to close this issue or do we want to wait for `USE_UPDATED_SIGNING_UI` to be completely removed?

**Comment by Shadowfiend** [comment]
Let's hold it for `USE_UPDATED_SIGNING_UI`. Hope to knock that out next week.
