### ISSUE TITLE
Can't connect to Eigenlayer

### ISSUE THREAD

**Issue by jagodarybacka** [tahowallet/extension#3453]
Metamask option is no longer working regardless if Taho is default wallet or not.
https://www.eigenlayer.xyz/
![image](https://github.com/tahowallet/extension/assets/20949277/de85ca6a-a5fa-45d4-b72f-f688f681aa19)

**Comment by Shadowfiend** [comment]
This will be fixed with the new dApp connections work, when we’ll enable metamask impersonation across the board. Hoping to land it this week.
