### ISSUE TITLE
Handle super long asset amounts better

### ISSUE THREAD

**Issue by jagodarybacka** [tahowallet/extension#3459]
Let's handle these long asset names and amounts without overflowing the screen

![image](https://github.com/tahowallet/extension/assets/20949277/d73f9b84-4776-4737-822b-691f825d4391)
![image](https://github.com/tahowallet/extension/assets/20949277/4b483fdb-bbdc-46bf-9322-dd8c021239b9)

**Comment by jagodarybacka** [comment]
@VladUXUI could you suggest how to handle them?

**Comment by xpaczka** [comment]
This is already done
