### ISSUE TITLE
Caching assets in redux is blocking UI

### ISSUE THREAD

**Issue by jagodarybacka** [tahowallet/extension#3466]
Caching assets in redux is blocking UI and it can take even 1-2s.

https://github.com/tahowallet/extension/blob/main/background/main.ts#L1065

I've changed that function to:

```javascript
    this.indexingService.emitter.on("assets", async (assets) => {
      console.log(assets.length)
      const t1 = performance.now()
      await this.store.dispatch(assetsLoaded(assets))
      const t2 = performance.now()
      console.log("asssets took", t2 - t1)
    })
```

And I got these results:
<img width="300" alt="image" src="https://github.com/tahowallet/extension/assets/20949277/058b4495-5621-424a-8750-c9db5ebf63cb">
Sometimes it's even >2s:
<img width="344" alt="image" src="https://github.com/tahowallet/extension/assets/20949277/c46e46fe-814d-478b-af41-938d82e27a2a">

Let's try to refactor the code so at least UI is not getting blocked for so long.

_Originally posted by @jagodarybacka in https://github.com/tahowallet/extension/issues/3264#issuecomment-1584568809_

**Comment by hyphenized** [comment]
Seems to be no longer an issue after #3561 and #3526, further improved by #3579
