### ISSUE TITLE
Argon2 integration

### ISSUE THREAD

**Issue by Shadowfiend** [tahowallet/extension#3470]
Upgrade the use of PBKDF2 to use Argon2 instead using https://github.com/antelle/argon2-browser .

Considerations:
- Upgrades should be transparent to the user; the first time the user enters their passphrase in the extension after upgrading, all historical vaults should be decrypted using the PBKDF2-derived key and then re-encrypted using the Argon2 key.
- We should bump the encrypted vault version to 2 for vaults that were encrypted using an Argon2-derived key. This will make it easier to determine later on whether an upgrade was or was not performed.
- We should register an analytics event when this occurs, so we can have a sense of how many users who have opted into analytics have been upgraded vs how many might remain on an older implementation.

Specific example references:
- Basic example in the argon2 repo: https://github.com/antelle/argon2-browser/blob/master/examples/node/argon2-demo-node.js
- More advanced example from an app using it: https://github.com/keeweb/keeweb/blob/develop/app/scripts/util/kdbxweb/kdbxweb-init.js#L11

**Comment by jagodarybacka** [comment]
https://github.com/tahowallet/extension/pull/3502 merged to feature branch
