### ISSUE TITLE
Custom auto lock

### ISSUE THREAD

**Issue by Shadowfiend** [tahowallet/extension#3471]
https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?type=design&node-id=19917-393091&t=fyoGFeYaBK5ATloJ-4

This config value will replace the constants `MAX_KEYRING_IDLE_TIME` and `MAX_OUTSIDE_IDLE_TIME`:

https://github.com/tahowallet/extension/blob/e3cad978d45a3528d3df9e87bb772810486c003d/background/services/keyring/index.ts#L25-L26

For now, the two should end up with the same value.

It would make sense for `KeyringService` to gain a dependency on `PreferencesService` and update its internal lock time based on configuration adjustments via event emissions. When that setting is updated, it would probably also make sense to call `autolockIfNeeded`, so that if the user drops the max idle time to an amount that is < the current idle time, the keyring locks immediately.

**Comment by jagodarybacka** [comment]
Already merged to the feature branch
