### ISSUE TITLE
Reload loop on saddle.finance

### ISSUE THREAD

**Issue by jagodarybacka** [tahowallet/extension#3500]
After connecting to the Saddle's [veSDL page](https://saddle.exchange/#/vesdl) dapp is stuck in relaoding loop and UI is broken. Let's investigate if we can do something about it on our side. This dapp is still broken even on builds with new dapp connections fixes https://github.com/tahowallet/extension/pull/3492

**Comment by Shadowfiend** [comment]
I'm seeing a bunch of “block range is too wide” stuff errors in the logs, so this is likely the same as #3536.

**Comment by jagodarybacka** [comment]
Stale
