### ISSUE TITLE
Spike galxe credential for Taho swap

### ISSUE THREAD

**Issue by kkosiorowska** [tahowallet/extension#3504]
## Problem
Difficult for us to gather holistic information about people that swap in Taho

## What we actually need

1. We need a way to to gather information and be able to query it with different filters.
2. We need to be able to filter by:

- Network
- Date
- Swap pairs (ex: USD/KEEP)
- address: #number of swaps
- address: Total $amount of swaps

This filtering doesn't need a UI

## What is this for
Our first usecase is going to be on www.galxe.com, used as a credential.
Can see more details about it here [Galxe Docs](https://docs.galxe.com/developer/guide/subgraph-cred)
[Subgraphs](https://thegraph.com/docs/en/developing/creating-a-subgraph/) are a product of The Graph that allow us to collect, process and store data.

**Comment by kkosiorowska** [comment]
**Some notes**

Work on the subgraph should start by defining smart contracts and selecting a network. To trace swaps for Taho wallet we should use the 0x Exchange Proxy [address](https://etherscan.io/address/0xDef1C0ded9bec7F1a1670819833240f027b25EfF#code) for the mainnet.

The resulting swap transactions should be filtered out if they were executed from a Taho wallet. This can be done using the community multisig address -`0x99b36fDbC582D113aF36A21EBa06BFEAb7b9bE12`.

Potential problems:
> - swaps to ETH have no fee -> no interaction with the multi-sig contract address
> - swaps to WETH were often wraps instead, and also had no interaction with the multi-sig
> - specific swap routings involving WETH also did not have interaction with the multi-sig, don’t recall the details anymore

Setting up your own Subgraph takes some time and is not the easiest way to go. It seems that we could start with the work already prepared Subgraph and make some changes to suit our needs. 

- https://github.com/0xProject/0x-exchange-proxy-subgraph/
- https://github.com/0xProject/ep-subgraph

**Steps to set up galxe credential for Taho swap:**

1.  Create a [Subgraph](https://thegraph.com/studio/?show=Create). Choose an indexed blockchain. Subgraph code should be deployed.
2. Create new curated Credentials on [Galxe](https://galxe.com/mycredentials). Select Supgraph type. Create and complete custom query and expression field. The endpoint field should be completed to the correct subgraph. The link can be found on [Subgraph Studio](https://thegraph.com/studio).

**Helpful links**
- Subgraph for [0x-exchange-proxy](https://thegraph.com/explorer/subgraphs/5fnrBcJSbnSZMBgFrK4TwTtYHBdgDa4raZiTm5nm79ps?view=Overview&chain=mainnet). You can use playgroud to search for transactions for a test wallet. 

  - [Github repository](https://github.com/0xProject/ep-subgraph)
  - Get basic swap information for a specific address. 
  

  ```
  {
    swaps(where: { taker: "0x0581470a8b62bd35dbf121a6329d43e7edd20fc7" } ) {
      inputToken {
        symbol
      }
      outputToken {
        symbol
      }
      transaction {
        id
        timestamp
      }
    }
  }
  ```

- [The Uniswap Subgraph](https://docs.uniswap.org/api/subgraph/overview)
- [AssemblyScript Migration Guide](https://thegraph.com/docs/en/release-notes/assemblyscript-migration-guide/) - Solves the problem of api version upgrade

**Comment by Shadowfiend** [comment]
Is this spike done? If so let's go ahead and close the issue. If not, what is left?

**Comment by kkosiorowska** [comment]
I think we can close this task as the example subgraph has been done and is able to track swaps from the Taho wallet. 

https://api.studio.thegraph.com/query/49074/taho-swap-optimism/v0.0.1
