### ISSUE TITLE
High gas fees on Optimism

### ISSUE THREAD

**Issue by jagodarybacka** [tahowallet/extension#3515]
These txs paid way too high gas fee for a swap, to be investigated.

https://optimistic.etherscan.io/tx/0x01236edd7388d6306e0920bd7a410732f52e3c6f2d4f3a73509f40991b910aeb
https://optimistic.etherscan.io/tx/0xb5621da06d967ccb7e804a8f460e9e75024f0cd18ad9fe6bec77052b115caeef

**Comment by am1993421** [comment]
https://optimistic.etherscan.io/tx/0x129560153ddb0d7f4de31af9870bb217084a8adf184cf98787d632d32cc616a1
https://optimistic.etherscan.io/tx/0x82d083afaeca0a3f94d07e337ece3cd90864439bc4fbd8b61da2e757495851c5

Additions to the same issue

**Comment by am1993421** [comment]
https://optimistic.etherscan.io/tx/0x129560153ddb0d7f4de31af9870bb217084a8adf184cf98787d632d32cc616a1
https://optimistic.etherscan.io/tx/0x82d083afaeca0a3f94d07e337ece3cd90864439bc4fbd8b61da2e757495851c5

Additions to the same issue
