### ISSUE TITLE
Issue with fetching the token list form the Yearn

### ISSUE THREAD

**Issue by kkosiorowska** [tahowallet/extension#3521]
We are currently unable to retrieve tokens from the Yearn list.  We receive the below error in the console. 

![Screenshot 2023-07-04 at 11 57 26](https://github.com/tahowallet/extension/assets/23117945/fcdad172-3dea-4061-8390-d988509cbef9)

**Comment by mhluongo** [comment]
This is maybe the 3rd time the URL has broken or changed :(
