### ISSUE TITLE
Taho doesn't work on stake.lido.fi

### ISSUE THREAD

**Issue by mhluongo** [tahowallet/extension#3532]
Despite being officially supported by Lido, trying to connect on mainnet (only Taho enabled) yields this, regardless of the network selected at connection time or in the wallet

![Screenshot from 2023-07-05 22-37-52](https://github.com/tahowallet/extension/assets/427505/9af462c3-0d11-4a8c-b6b5-b0faaa76908e)

**Comment by Shadowfiend** [comment]
All evidence points to this being fixed in #3492 , which should be going out in next week's release. Would appreciate it if you could double-check, but understand if there's no time.

**Comment by mhluongo** [comment]
Turns out I'm actually just trying to use Lido today, so uh... maybe there will be :)

**Comment by mhluongo** [comment]
Closed by #3492
