### ISSUE TITLE
"Add Network" navigation issue

### ISSUE THREAD

**Issue by mhluongo** [tahowallet/extension#3537]
![Screenshot from 2023-07-08 15-03-56](https://github.com/tahowallet/extension/assets/427505/de1f21d4-81eb-4e4b-a92a-be000421cd91)

After trying to add a new network from chainlist.org, the user gets stuck on the "Add Network" page.

To replicate

- [ ] Click "Add Network"
- [ ] Click the link to chainlist.org
- [ ] Re-open Taho. You'll be on the "Add Network" page
- [ ] Try to click "back". There should be a half-animation and no navigation

**Comment by Shadowfiend** [comment]
I believe this is a duplicate of https://github.com/tahowallet/extension/issues/3365, yes?

**Comment by beemeeupnow** [comment]
> I believe this is a duplicate of #3365, yes?

Yep. For some reason in my testing it only happened the first time I added a custom network.

**Comment by jagodarybacka** [comment]
Duplicate of https://github.com/tahowallet/extension/issues/3365
