### ISSUE TITLE
Activity list item content wraps inconsistently

### ISSUE THREAD

**Issue by hyphenized** [tahowallet/extension#3545]
<img width="375" alt="image" src="https://github.com/tahowallet/extension/assets/28708889/c4ef9547-a020-429a-a594-fccdf6def7dc">
<br><br>
The amount of bananas should appear on the same line.
<br><br>
<img width="376" alt="image" src="https://github.com/tahowallet/extension/assets/28708889/f0fc616e-362d-49d8-a97c-9a0248af19ea">
<br><br>
Also, the ENS name should collapse with an ellipsis here after 10 characters, similar to addresses.

**Comment by xpaczka** [comment]
This one is already resolved
