### ISSUE TITLE
Support Ethereum Sepolia test network

### ISSUE THREAD

**Issue by fulldecent** [tahowallet/extension#3554]
### Discord Discussion Link

x

### What would you like to be able to do?

Currently when using Taho and doing Settings > Show test networks, you can see only Goerli.

Here is how that looks:

<img width="376" alt="Screenshot 2023-07-18 at 15 43 32" src="https://github.com/tahowallet/extension/assets/382183/849ca573-5f62-4db2-88ef-8c307aecaabf">

---

However, Goerli is already deprecated.

Source: https://ethereum.org/en/developers/docs/networks/

Sepolia should be supported by Taho as well as or better than Goerli.

**Comment by jagodarybacka** [comment]
Hey, we have a feature to add any network you want using [Chainlist](https://chainlist.org/). You can add Sepolia by clicking on the `Add network` button you can see at the bottom of your screenshot 😉 
We will most likely remove Goerli from the list at some point.

**Comment by fulldecent** [comment]
You are describing a workaround. But this feature should be implemented in Taho as a first-class support.

**Comment by Shadowfiend** [comment]
Jagoda is saying we're not convinced first class hardcoded support for specific Ethereum testnets is a useful thing to spend code on if it's trivial to add testnets across chains for those who need them. Separating testnets in the system *is* useful for various reasons, and we're pondering and open to ways to approach that (though unfortunately it's not at the top of the pile). 

Open to hearing arguments to the contrary, of course.

**Comment by fulldecent** [comment]
More people should be using test nets than should be using main nets.

This is because everybody should use a test net account before they spend money. 

I use test net accounts in every class I teach. 

For example I am teaching a class today and I changed my slides to highlight Taho instead of MetaMask. But I was surprised that Taho does not fully support test nets. 

Please note that every click required and every additional logo on the screen (eg the one you now need to see for this workaround) results in some confusion for each student. 

When you see a different logo on the screen this means that Taho isn't providing first class support. But Ethereum says that is the recommended test net. 

Therefore it is clear the Taho is not following Ethereum's recommendations.

This is in the middle of a class where I am teaching people to be skeptical and all the myriad ways that people can take their money. 

---

Also in this class I tell people to get Goerli test net tokens. And currently that is impossible to do anonymously. 

Therefore Taho provides a much degraded experience versus the competition in classroom settings. 

For example here is the homework I am giving students today. 

HTTPS://phor.net/homework.pdf
