### ISSUE TITLE
Not able to deposit assets on Velodrome

### ISSUE THREAD

**Issue by kkosiorowska** [tahowallet/extension#3590]
Currently, depositing assets with Taho is not working on [Velodrome](https://velodrome.finance/). We get the following error.  It is not working also for MM but it seems that work for Coinbase wallet.

Try to find the cause and inform the Velodrome or fix it on Taho wallet.

<img width="1229" alt="Screenshot 2023-08-02 at 11 05 10" src="https://github.com/tahowallet/extension/assets/23117945/d2022146-d758-49a7-a28c-d8038ceb6efc">

**Comment by beemeeupnow** [comment]
worked for me while testing v0.47.0
