### ISSUE TITLE
infinite loop on guild.xyz only when Taho as default is selected

### ISSUE THREAD

**Issue by beemeeupnow** [tahowallet/extension#3604]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Trying to use guild.xyz with Taho after having logged in to the same page on another browser/machine with the same account.

This is something I've been encountering recently but could not find the cause of. (did not happen often)

During testing I finally found a way to force the issue to happen.

Note: Taho is the _only_ wallet installed during this issue

### What did not work?

When Taho is the default (despite being the only wallet installed) some looping issue is encountered.

Setting to not be default resolves the issue.

* connect to https://guild.xyz/ with Taho while the Taho as default is enabled, sign the login message
* in a different browser or machine connect to https://guild.xyz/ with the same wallet address, sign the login message
* on the first browser/machine refresh the page
* it should indicate that you need to log in again and then pop up the wallet selection, which may appear to flicker
* the browser console will be flooded with messages if the issue occurs and you will _not_ get a popup from the wallet to sign the login message
* open the extension and toggle the default at the top of the UI to not be Taho
* the looping should stop, but you must then refresh the page to have things work again
* you should now be presented with the login prompt ("Verify account")

### Version

v0.47.0

**Comment by Shadowfiend** [comment]
Think I hunted this down, more tomorrow!

**Comment by beemeeupnow** [comment]
Any chance this can be addressed soon? I know yall have been busy with other amazing things, but this is a pain point that new users are very likely to encounter.

Confirmed still present in v0.50.0 if Taho as default is enabled

**Comment by Shadowfiend** [comment]
I had a semi-fix here that I haven't had a chance to finish. Might see if I can dust it off and ship a fix next week.
