### ISSUE TITLE
Curve DAO dapp not able to connect to Taho 

### ISSUE THREAD

**Issue by Lazervike** [tahowallet/extension#3612]
### Discord Discussion Link

I have a dumb q: I just try to connect Taho onto curve without metamask installed and I'm not sure how I can get that running

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Connecting to the Curve DAO dApp : https://dao.curve.fi/

I am on Chrome desktop and do not have MetaMask installed.

### What did not work?

The wallet connect overlay doesn't show Taho, and when trying to connect via MetaMask it would ask me to download MetaMask instead.

### Version

v0.47.0

**Comment by Lazervike** [comment]
Feel free to ping me on this.

**Comment by Shadowfiend** [comment]
Looks like dao.curve.fi does MetaMask detection in a way that we aren't handling right now when MetaMask isn't present. Should be fixable quickly.
