### ISSUE TITLE
cannot connect metamask in http://mint.starheroes.community/

### ISSUE THREAD

**Issue by NCLnclNCL** [tahowallet/extension#3617]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

i connet to it with metamask options,rabby wallet can easily spoof the connection why can't this one

### What did not work?

it show need install metamask

### Version

v0.48.0

**Comment by Shadowfiend** [comment]
Version 0.48.0 isn't published on the Chrome store yet, so I'm puzzled as to why you're saying you have this version.

Additionally, this is working for me:

<img width="931" alt="Screenshot 2023-09-02 at 22 47 53" src="https://github.com/tahowallet/extension/assets/8245/d0f7f041-935f-41f2-af98-513799d82a6a">

Are you sure you have Taho set to impersonate MetaMask? See the toggle at the top of the wallet popover.

**Comment by Shadowfiend** [comment]
Ah, it's possible you're trying to use Base without having added it, because this site doesn't prompt you to add the network, it assumes you already have it added. Please go to Chainlist and add Base (https://chainlist.org/?search=Base) to Taho, and then try to connect again on https://mint.starheroes.community/

**Comment by Shadowfiend** [comment]
Related: please don't post a GitHub issue without discussing in Discord. It is typically our policy to close these immediately; here is the relevant section of the form you filled out:

<img width="840" alt="Screenshot 2023-09-02 at 22 52 34" src="https://github.com/tahowallet/extension/assets/8245/21840166-6651-4f53-975b-f5b76e1c01f7">

I hope the above helps, but if it does not, please find your way to Discord where the community can try to help out before filing a bug. I will close this for now.

**Comment by NCLnclNCL** [comment]
> Related: please don't post a GitHub issue without discussing in Discord. It is typically our policy to close these immediately; here is the relevant section of the form you filled out:
> 
> <img alt="Screenshot 2023-09-02 at 22 52 34" width="840" src="https://user-images.githubusercontent.com/8245/265239583-21840166-6651-4f53-975b-f5b76e1c01f7.png">
> I hope the above helps, but if it does not, please find your way to Discord where the community can try to help out before filing a bug. I will close this for now.

why this dont auto add chain ??
