### ISSUE TITLE
`transaction.chainId/signature.v mismatch` error when signing transactions using Ledger

### ISSUE THREAD

**Issue by michalinacienciala** [tahowallet/extension#3647]
I did some tests of staking in the Subscape dapp (I used the stage-live deployment) on Ethereum Sepolia and although some staking transactions were successful, some failed with the following errors in the wallet logs:
```
logger.ts:208 Error encountered! ledgerID: LEDGER_NANO_S_0x43866d77672dd19252e8ea2274ecece9c62d3262 transactionRequest: [object Object] error: Error: transaction.chainId/signature.v mismatch (argument="signature", value={"r":"0x2b069505b96a272c34d3820efdec59442b4424d4362bec7af2e368150df6a9c3","s":"0x4efc2c085a3688549d2ede91647168de8dbdd45434ab602fcefcaf69c906aaf6","v":843518}, code=INVALID_ARGUMENT, version=transactions/5.7.0)
```
and
```
Error signing transaction Error: transaction.chainId/signature.v mismatch (argument="signature", value={"r":"0x2b069505b96a272c34d3820efdec59442b4424d4362bec7af2e368150df6a9c3","s":"0x4efc2c085a3688549d2ede91647168de8dbdd45434ab602fcefcaf69c906aaf6","v":843518}, code=INVALID_ARGUMENT, version=transactions/5.7.0)
    at Logger.makeError (index.js:224:23)
    at Logger.throwError (index.js:233:20)
    at Logger.throwArgumentError (index.js:236:21)
    at _serialize (index.js:204:20)
    at serialize (index.js:221:16)
    at index.ts:415:35
```
and
```
ProviderBridgeService.routeContentScriptRPCRequest
Error processing request
```

I used version `0.50.0c1e7552` of the wallet and used Ledger Nano S (`2.60.0`) with Ethereum app (`1.10.1`) for signing.

Here are the tests that I did:
TEST 1. Stake 2 TAHO. Staking failed with a different error (`Transfer amount exceeds spender allowance`) - not in scope of this issue
TEST 2. Stake 2 TAHO. Both transactions successful
TEST 3. Stake 3 TAHO. `Token approval` successful, `Contract interaction` failed with `transaction.chainId/signature.v mismatch`
TEST 4. Stake 3 TAHO. `Contract interaction` failed with `transaction.chainId/signature.v mismatch`
TEST 5. Stake 3 TAHO. `Contract interaction` successful
TEST 6: Stake 1 TAHO. Both transactions successful
TEST 7: Stake 2 TAHO. Approve asset spend successful, Contract interaction failed with `transaction.chainId/signature.v mismatch`
TEST 8: Stake 2 TAHO. Contract interaction failed with `transaction.chainId/signature.v mismatch`
TEST 9: Stake 2 TAHO. Contract interaction failed with `transaction.chainId/signature.v mismatch`
TEST 10: Stake 2 TAHO. Contract interaction failed with `transaction.chainId/signature.v mismatch`
TEST 11: Stake 2 TAHO. Contract interaction failed with `transaction.chainId/signature.v mismatch`
TEST 12: Stake 2 TAHO. Contract interaction failed with `transaction.chainId/signature.v mismatch`

Video covering tests 6-12:

https://github.com/tahowallet/extension/assets/78352137/c299681f-74b5-4ce4-ba4f-09b7552a8e5c

Looking at the results, there's no clear rule about which transactions fail and which are successful.

I wonder if the problem may be caused by similar issue as discussed here: https://github.com/ethers-io/ext-signer-ledger/issues/6#issuecomment-1646196739. In this issue, bumping ledger libraries in `ether.js` (https://github.com/ethers-io/ethers.js/pull/1370/files) has helped. But we already use higher versions than those...

**Comment by michalinacienciala** [comment]
Tried other dApps and networks:

TEST 13. Swap 0.01ETH to WETH on Ethereum Sepolia on Uniswap. Signing `Sign transaction` successful (14:05)

TEST 14. [MM Test Dapp](https://metamask.github.io/test-dapp/). Arbitrum Sepolia. Send EIP 1559 Transaction. Fail, `transaction.chainId/signature.v mismatch`

... (will update here with other results)

**Comment by andreachapman** [comment]
@michalinacienciala - I've done two tests on https://bridge.arbitrum.io/. I've sent from Sepolia to Arbitrum Sepolia and I didn't get the `transaction.chainId/signature.v mismatch` error on either. I did see the 429 that you mentioned in another thread but for the purposes of this test, I was able to complete the trxn from the ledger.

Here's the video for one:

https://github.com/tahowallet/extension/assets/135037801/2af97c2f-da50-4b1d-95e3-80c65c2231fc

And the scan site: https://sepolia.etherscan.io//tx/0x7e0c9cafb6b5fa5725e2451034c74cffb4c9307640b6fa9af8b3fc2667d32167

And then I also did a test the other way from Arbitrum Sepolia to Ethereum Sepolia and I didn't get the error there either: 

https://github.com/tahowallet/extension/assets/135037801/3c9a1b66-4266-4d06-b8b3-347cb0d03550

https://sepolia.arbiscan.io//tx/0x32aff882dbabd3b55f31aba055fbdfcb588651c1038fe6063142b6e94419788b

Leder Nano X with Version 1.10.2

**Comment by michalinacienciala** [comment]
@andreachapman , could you do maybe 2 more retries of the test with sending from the Arbitrum Sepolia (only if you have time)?

**Comment by michalinacienciala** [comment]
> So it's definitely not consistent from what I'm seeing. But very interesting that I did like 5 tests and never saw that error until right after I moved TAHO to my ledger wallet.

Hmm, interesting. The account I'm seeing all those failures on also has TAHO. So it may have something to do with it - although I'm not 100% sure, as in some cases I did have TAHO and was able to do successful transactions (e.g in TEST 2, see video below)

Uploading Screen Recording 2023-10-27 at 10.08.18.mov…

**Comment by michalinacienciala** [comment]
My tests 1-22 were all done on the same Ledger account (`0x43866d77672dd19252e8ea2274ecece9c62d3262`) which had TAHO.

For the TEST 23 I've added another, clean Ledger account (`0xbb510ca2cf69e40000a415ccee2009467c10afb3`) to wallet and send there some ETH. No TAHO was on that account. Then I did a test transaction on [MM Test Dapp](https://metamask.github.io/test-dapp/) on Arbitrum Sepolia and for the first time on that network there I didn't get a failure...

I'll do one more try and then send some TAHO to that account and try one more time. I'll update this comment once I have the results.

**Comment by michalinacienciala** [comment]
Let me post a summary here:
The only network we see the problem with `transaction.chainId/signature.v mismatch` occurring on is Arbitrum Sepolia. Issue occurs both for accounts which have TAHO and those which don't. But the issue does not occur for all transactions on Arbitrum Sepolia - sometimes we can have a streak of several successful transactions in a row and then get failures. Sometimes most transactions are failing, but there are single ones that are successful. There's no evident rule behind that.
Issue was seen on all the Ledger / Ethereum app versions that we've tested on:
Ledger Nano S & Ethereum 1.10.1
Ledger Nano S & Ethereum 1.10.3
Ledger Nano X & Ethereum 1.10.2

**Comment by michalinacienciala** [comment]
Unfortunately, I still see the issue. I've tested on builds from https://github.com/tahowallet/extension/pull/3650 and https://github.com/tahowallet/extension/pull/3613. In both cases I got the `transaction.chainId/signature.v mismatch` when unstaking (on a prod Subscape).

Here's a video from testing on a build from https://github.com/tahowallet/extension/pull/3613: https://drive.google.com/file/d/1WxLyCzRQPbAdBOrB93JXc9Yj4Z1yNBRb/view?usp=drive_link (warning: the file is big (>400MB)).

**Comment by michalinacienciala** [comment]
Ok, fixed after latest changes in https://github.com/tahowallet/extension/pull/3613.
Verified on a release build from https://github.com/tahowallet/extension/pull/3652.
