### ISSUE TITLE
Subscape access in wallet extension

### ISSUE THREAD

**Issue by Shadowfiend** [tahowallet/extension#3669]
Goal is to be able to access Subscape easily from the Taho wallet. Should be tucked away, and only appear if the user has beta/testnet TAHO.

Figma link:
https://www.figma.com/file/bEY6fqdX6LiPKP7J1eg7Ag/TokenLaunch-Dapp?type=design&node-id=5392-10346&mode=design&t=c4t7SlkfyTG4R6ro-4

**Comment by VladUXUI** [comment]
@Shadowfiend i was thinking this would be open to everybody, not only to users that have testnet Taho.
It simplifies mechanics, and we don't get a "were did that button dissapear" if users is on another address that doesn't have TAHO.

It also might give us a small boost in visibility across people that aren't aware/active, but can still sign up for waitlist

**Comment by VladUXUI** [comment]
Discussed with Jagoda, but also adding here, it should have an expiration date. Dec 14th
