### ISSUE TITLE
Other accounts are not loaded from seed phrase

### ISSUE THREAD

**Issue by fulldecent** [tahowallet/extension#3727]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Load a wallet seed phrase from MetaMask and access multiple accounts in that wallet

### What did not work?

Only the first account loaded

### Version

None

**Comment by Shadowfiend** [comment]
Did you inquire about this in Discord? Additional addresses can be added from the settings menu:

<img width="410" alt="Screenshot 2024-01-18 at 09 13 44" src="https://github.com/tahowallet/extension/assets/8245/ed59dfe2-26a6-422e-afc3-3c6b5c102dd4">
<img width="451" alt="Screenshot 2024-01-18 at 09 14 25" src="https://github.com/tahowallet/extension/assets/8245/980f8177-6d3c-4d7b-b7dc-9abd168d2e57">

There is an unscheduled idea to unify that experience with the one used for Ledger, but for the time being it's more rudimentary.

**Comment by fulldecent** [comment]
Aha, thank you!
