### ISSUE TITLE
In Arc browser (Chrome) opening Taho is annoying

### ISSUE THREAD

**Issue by fulldecent** [tahowallet/extension#3728]
### Discord Discussion Link

.

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

You have to keep finding and clicking the Taho extension to open the window. In Arc this is buried two clicked deep.

Instead Taho should support a "full window" button which loads the interface as a browser tab that stays open.

### What did not work?

.

### Version

None

### Relevant log output

```shell
.
```

**Comment by mhluongo** [comment]
Have you tried the keyboard shortcut, `alt + T`?

**Comment by fulldecent** [comment]
Hmm, have not tried. Already uninstalled.

**Comment by mhluongo** [comment]
Closing this — Arc isn't a supported browser. For anyone else concerned here, consider trying the keyboard shortcut!
