### ISSUE TITLE
Use 4byte to look up all unknown transaction function signatures by selector

### ISSUE THREAD

**Issue by mhluongo** [tahowallet/extension#492]
Secure signing means users need to know the implication of what they're signing... otherwise the signature doesn't represent user consent. And for most users, a hex string ain't that.

We can use [4byte](https://4byte.directory) to look up function selectors to get additional metadata, making many otherwise inscrutable contract calls somewhat bearable. We can apply this in two places in the wallet to great success

- [ ] Show function signatures before a user signs a transaction
- [ ] Show function signatures in activities when we don't have a better visualization. More context on that problem space [here](https://github.com/tallycash/tally-extension/pull/400#discussion_r756425046)

cc @henryboldi as I know you want to see more tx introspection / activity metadata.

**Comment by tallysam** [comment]
This service no longer exists.

**Comment by Shadowfiend** [comment]
I believe it does fwiw, it's just at www.4byte.directory . The referencing commits seem to use the right format.
