### ISSUE TITLE
Dapp connections - when I connect my wallet, a brief error message displays

### ISSUE THREAD

**Issue by mr-michael** [tahowallet/extension#607]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

-

### What did not work?

This error message displays ... 

https://user-images.githubusercontent.com/7005061/145884246-cf99b131-90bd-4811-8e79-63df357691ab.mov

...right around the 12 second mark of:

<img width="463" alt="Screen Shot 2021-12-13 at 3 30 31 PM" src="https://user-images.githubusercontent.com/7005061/145884251-427bca98-a7b0-4ea1-a9e5-aa6c2dacd63b.png">

**Comment by mhluongo** [comment]
That message :rofl:

**Comment by Shadowfiend** [comment]
This doesn't seem to be happening anymore, closing.
