### ISSUE TITLE
Support adding an asset from a dApp

### ISSUE THREAD

**Issue by mhluongo** [tahowallet/extension#677]
dApps with long-tail assets include buttons to add the asset to an injected wallet. We should support whatever protocol is being followed... as well as proposing one for adding a token list.

[Alchemix](https://app.alchemix.fi/) is a great example, allowing you to add ALCX, alETH, and alUSD from the top right.

When a user adds a new asset, we should do a balance check.

**Comment by mhluongo** [comment]
![Screenshot from 2021-12-15 22-22-05](https://user-images.githubusercontent.com/427505/146302428-6c9af56c-6544-4f51-81c4-5b59cc075e88.png)

Here's the error we see if we try to do it today with Tally

**Comment by VladUXUI** [comment]
I this something that DApps request us to do? Meaning that user will need to just confirm that they want to add the token or is this something that users need to add manually.

I really hope it's the former 😅

**Comment by mhluongo** [comment]
Correct!

**Comment by beemeeupnow** [comment]
added via #3285
