### ISSUE TITLE
Integrate Tally with the new web3-react architecture

### ISSUE THREAD

**Issue by greg-nagy** [tahowallet/extension#849]
web3-react has undergone a huge change in architecture, and it's still in beta.
But it would be awesome, to have native integration for Tally in the new architecture.

Ref #38 

PR in web3-react repo: https://github.com/NoahZinsmeister/web3-react/pull/498

**Comment by Shadowfiend** [comment]
Going to kill this, as we don't have the bandwidth to manage directly.
