### ISSUE TITLE
Seed gen - UX bug - when I close Tally window during seed gen, a new seed is created

### ISSUE THREAD

**Issue by mr-michael** [tahowallet/extension#908]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I created a wallet for testing, recorded the seed, then prepared to re-enter it.

During this time, I clicked on the top of chrome and it closed Tally...

### What did not work?

... when I re-open Tally, I'm dropped back into the wallet but the seed I recorded is now gone. Eek!

**Comment by henryboldi** [comment]
The idea is that https://github.com/tallycash/extension/pull/901 will be the fix here

**Comment by SJQuality** [comment]
Clicking in the Chrome window not on Tally closes the Tally app at any point from the initial "Welcome to Tally Ho!" page all the way through the creation of wallet process and verification. So, if the user mis-clicks at any point after generating the phrase, the app resets, and the user must repeat the entire process and will have to generate a new phrase. This includes "Write down" page and the "Verification" page. 

looks like #901 was merged a while ago, but this issue persists.

**Comment by henryboldi** [comment]
Upgrading to high severity because the number of people reporting this UX issue. However, this isn't in my current sprint. Would love for someone to pick this up 🙇

**Comment by Shadowfiend** [comment]
We shipped tabbed onboarding, which should resolve the concern here. Closing.
